apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default  # Replace with your namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: myapp.example.com  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service  # Replace with your service name
            port:
              number: 80  # Replace with your service port
  tls:
  - hosts:
    - myapp.example.com  # Replace with your domain
    secretName: my-tls-secret  # This should match the name of the TLS secret you created
